//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnSherlockAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquityReleaseLead
    {
        public int ID { get; set; }
        public int LeadId { get; set; }
        public int Age { get; set; }
        public System.DateTime Dob { get; set; }
        public int HomeValue { get; set; }
        public int OutstandingMortgageValue { get; set; }
        public int AgeType { get; set; }
        public int EquityType { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int DeleteStatus { get; set; }
    
        public virtual CommonLead CommonLead { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
