//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnSherlockAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanLead
    {
        public int ID { get; set; }
        public int LeadId { get; set; }
        public System.DateTime Dob { get; set; }
        public int Age { get; set; }
        public int LoanPurpose { get; set; }
        public System.DateTime PreviousAddressSince { get; set; }
        public string PreviousPostCode { get; set; }
        public string PreviousCity { get; set; }
        public string PreviousAddress { get; set; }
        public string EmployerName { get; set; }
        public System.DateTime EmployedSince { get; set; }
        public string Occupation { get; set; }
        public bool BeenInDebt { get; set; }
        public bool LoanGurantor { get; set; }
        public string TotalCreditors { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public string GurantorName { get; set; }
        public string GurantorPhone { get; set; }
        public string GurantorEmail { get; set; }
        public int Period { get; set; }
        public int LoanEmploymentStatus { get; set; }
        public int LoanCreditRating { get; set; }
        public int LoanAnnualIncome { get; set; }
        public int LoanCountryOfResidence { get; set; }
        public int LoanMaritalStatus { get; set; }
        public int MortgageBalance { get; set; }
        public int LoanPropertyValue { get; set; }
        public bool HomeOwner { get; set; }
        public int MortgageLoanValue { get; set; }
        public System.DateTime AddressStartDate { get; set; }
        public bool HadBankruptcy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int DeleteStatus { get; set; }
    
        public virtual CommonLead CommonLead { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
