//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnSherlockAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PensionLead
    {
        public int ID { get; set; }
        public int LeadId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int DeleteStatus { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public int Age { get; set; }
        public System.DateTime Dob { get; set; }
        public Nullable<int> PersonalPensionType { get; set; }
        public Nullable<int> PensionPremiumType { get; set; }
        public Nullable<int> Pensionvalue { get; set; }
        public Nullable<int> Pensiontype { get; set; }
        public Nullable<int> PensionAccessFund { get; set; }
        public Nullable<int> ExistPensions { get; set; }
        public string PensionTypeOther { get; set; }
        public bool IsCurrentlyPayingMoney { get; set; }
        public Nullable<int> TotalPensionValue { get; set; }
    
        public virtual CommonLead CommonLead { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
