//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnSherlockAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> GeneratedDateTime { get; set; }
        public Nullable<System.DateTime> TransferDateTime { get; set; }
        public Nullable<int> BuyerIntegrationTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> TransferredTo { get; set; }
        public Nullable<int> ProductSlabId { get; set; }
        public Nullable<bool> IsActualPrice { get; set; }
        public Nullable<int> LeadId { get; set; }
        public string BuyerReturnLeadId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> Return { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> BuyerProductScheduleId { get; set; }
    
        public virtual BuyerMaster BuyerMaster { get; set; }
        public virtual ProductSlab ProductSlab { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
